// 听歌识曲 — NetEase Cloud Music song IDs
// Audio URL: https://music.163.com/song/media/outer/url?id={id}.mp3
// start: seconds into the song to begin the clip

const DATA = [
  { id: 186016,     name: '晴天',           artist: '周杰伦',       start: 49,  choices: ['晴天','稻香','七里香','简单爱'] },
  { id: 418603077,  name: '告白气球',       artist: '周杰伦',       start: 38,  choices: ['告白气球','爱情废柴','不该','说好不哭'] },
  { id: 185709,     name: '稻香',           artist: '周杰伦',       start: 40,  choices: ['稻香','晴天','听妈妈的话','阳光宅男'] },
  { id: 185811,     name: '青花瓷',         artist: '周杰伦',       start: 52,  choices: ['青花瓷','东风破','菊花台','兰亭序'] },
  { id: 185894,     name: '菊花台',         artist: '周杰伦',       start: 30,  choices: ['菊花台','青花瓷','发如雪','将军'] },
  { id: 186137,     name: '双截棍',         artist: '周杰伦',       start: 20,  choices: ['双截棍','忍者','夜的第七章','龙战骑士'] },
  { id: 186001,     name: '七里香',         artist: '周杰伦',       start: 45,  choices: ['七里香','晴天','搁浅','漂移'] },
  { id: 375381,     name: '不想长大',       artist: 'S.H.E',        start: 35,  choices: ['不想长大','Super Star','中国话','恋人未满'] },
  { id: 375762,     name: 'Super Star',     artist: 'S.H.E',        start: 30,  choices: ['Super Star','不想长大','波斯猫','你曾是少年'] },
  { id: 375085,     name: '中国话',         artist: 'S.H.E',        start: 25,  choices: ['中国话','不想长大','SHERO','候鸟'] },
  { id: 385781,     name: '突然好想你',     artist: '五月天',       start: 50,  choices: ['突然好想你','温柔','如烟','恋爱ing'] },
  { id: 386538,     name: '温柔',           artist: '五月天',       start: 38,  choices: ['温柔','突然好想你','知足','爱情万岁'] },
  { id: 287035,     name: '遇见',           artist: '孙燕姿',       start: 40,  choices: ['遇见','天黑黑','逆光','我不难过'] },
  { id: 33206214,   name: '小幸运',         artist: '田馥甄',       start: 42,  choices: ['小幸运','你就不要想起我','我爱你','苦瓜'] },
  { id: 254432,     name: '后来',           artist: '刘若英',       start: 55,  choices: ['后来','很爱很爱你','成全','原来你也在这里'] },
  { id: 299075,     name: '我愿意',         artist: '王菲',         start: 40,  choices: ['我愿意','红豆','传奇','人间'] },
  { id: 299936,     name: '红豆',           artist: '王菲',         start: 35,  choices: ['红豆','我愿意','传奇','梦中人'] },
  { id: 25706282,   name: '夜空中最亮的星', artist: '逃跑计划',     start: 45,  choices: ['夜空中最亮的星','一万次悲伤','思念是一种病','要我怎么办'] },
  { id: 28815250,   name: '平凡之路',       artist: '朴树',         start: 50,  choices: ['平凡之路','那些花儿','白桦林','生如夏花'] },
  { id: 436514312,  name: '成都',           artist: '赵雷',         start: 48,  choices: ['成都','理想','南方姑娘','我记得'] },
  { id: 1330348068, name: '起风了',         artist: '买辣椒也用券', start: 40,  choices: ['起风了','云与海','不谓侠','像风一样'] },
  { id: 1430319727, name: '漠河舞厅',       artist: '柳爽',         start: 35,  choices: ['漠河舞厅','花海','蓝莲花','盛夏的果实'] },
  { id: 32507038,   name: '演员',           artist: '薛之谦',       start: 38,  choices: ['演员','认真的雪','动物世界','丑八怪'] },
  { id: 169185,     name: '认真的雪',       artist: '薛之谦',       start: 30,  choices: ['认真的雪','演员','动物世界','暗语'] },
  { id: 449818741,  name: '光年之外',       artist: 'G.E.M. 邓紫棋', start: 42, choices: ['光年之外','泡沫','爱你','新的心跳'] },
  { id: 233931,     name: '泡沫',           artist: 'G.E.M. 邓紫棋', start: 35, choices: ['泡沫','光年之外','倒数','走天涯'] },
  { id: 25640799,   name: '给我一个理由忘记', artist: '任然',       start: 40,  choices: ['给我一个理由忘记','有一种悲伤','执迷不悟','Fiction'] },
  { id: 29814898,   name: '可惜没如果',     artist: '林俊杰',       start: 45,  choices: ['可惜没如果','修炼爱情','她说','江南'] },
  { id: 85580,      name: '童话',           artist: '光良',         start: 48,  choices: ['童话','第一次','一起走到','背叛'] },
  { id: 176999,     name: '情非得已',       artist: '庾澄庆',       start: 25,  choices: ['情非得已','让我一次爱个够','老实情歌','命中注定'] },
];
